// Generated by Haxe 4.0.0-rc.2+77068e10c
(function () { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	console.log("src/Main.hx:5:","Hello, world!");
};
var React_Component = require("react").Component;
var coconut_ui_ViewBase = function(rendered,mounted,updated,unmounting) {
	React_Component.call(this);
	this.state = this.__snap();
	this.__rendered = rendered;
	this.__viewMounted = mounted;
	this.__viewUpdated = updated;
	this.__viewUnmounting = unmounting;
};
coconut_ui_ViewBase.__name__ = true;
coconut_ui_ViewBase.createFragment = function(attr,children) {
	var tmp = [React_Fragment,attr].concat(children);
	return React.createElement.apply(null,tmp);
};
coconut_ui_ViewBase.fromHxx = function(props) {
	return React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(coconut_ui_ViewBase),props);
};
coconut_ui_ViewBase.__super__ = React_Component;
coconut_ui_ViewBase.prototype = $extend(React_Component.prototype,{
	__snap: function() {
		var _gthis = this;
		return { vtree : new tink_core__$Lazy_LazyFunc(function() {
			return tink_state__$Observable_Observable_$Impl_$.get_value(_gthis.__rendered);
		})};
	}
	,componentDidMount: function() {
		var _gthis = this;
		this.__link = tink_state__$Observable_Observable_$Impl_$.bind(this.__rendered,null,function(_) {
			var tmp = _gthis.__snap();
			_gthis.setState(tmp);
		});
		if(this.__viewMounted != null) {
			this.__viewMounted();
		}
	}
	,componentDidUpdate: function(_,_1) {
		if(this.__viewUpdated != null) {
			this.__viewUpdated();
		}
	}
	,componentWillUnmount: function() {
		var this1 = this.__link;
		if(this1 != null) {
			this1.cancel();
		}
		if(this.__viewUnmounting != null) {
			this.__viewUnmounting();
		}
	}
	,reactify: function() {
		if(this.__rewrapped == null) {
			this.__rewrapped = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(coconut_ui__$ViewBase_Rewrapped),{ target : this});
		}
		return this.__rewrapped;
	}
	,shouldComponentUpdate: function(_,next) {
		return this.state.vtree.get() != next.vtree.get();
	}
	,render: function() {
		var ret = this.state.vtree.get();
		if(typeof ret == "undefined") {
			return null;
		}
		return ret;
	}
});
var coconut_ui_View = function(render,shouldUpdate,track,beforeRerender,mounted,updated) {
	this.__au = [];
	this.__bc = [];
	this.__bu = [];
	this._coco_revision = new tink_state__$State_SimpleState(0,null,null);
	this.viewId = coconut_ui_View.idCounter++;
	var _gthis = this;
	var firstTime = true;
	var last = null;
	var hasBeforeRerender = beforeRerender != null;
	var hasUpdated = updated != null;
	var lastRev = tink_state__$State_State_$Impl_$.get_value(this._coco_revision);
	coconut_ui_ViewBase.call(this,tink_state__$Observable_Observable_$Impl_$.auto({ f : function() {
		var curRev = tink_state__$State_State_$Impl_$.get_value(_gthis._coco_revision);
		if(track != null) {
			track();
		}
		if(firstTime) {
			firstTime = false;
		} else {
			if(curRev == lastRev && shouldUpdate != null && !shouldUpdate()) {
				return last;
			}
			var hasCallbacks = _gthis.__bc.length > 0;
			if(hasBeforeRerender || hasCallbacks) {
				tink_state__$Observable_Observable_$Impl_$.untracked(function() {
					if(hasBeforeRerender) {
						beforeRerender();
					}
					if(hasCallbacks) {
						var _g = 0;
						var _g1 = _gthis.__bc.splice(0,_gthis.__bc.length);
						while(_g < _g1.length) tink_core__$Callback_Callback_$Impl_$.invoke(_g1[_g++],false);
					}
				});
			}
		}
		lastRev = curRev;
		last = render();
		return last;
	}}),mounted,function() {
		var hasCallbacks1 = _gthis.__au.length > 0;
		if(hasUpdated || hasCallbacks1) {
			tink_state__$Observable_Observable_$Impl_$.untracked(function() {
				if(hasUpdated) {
					updated();
				}
				if(hasCallbacks1) {
					var _g2 = 0;
					var _g11 = _gthis.__au.splice(0,_gthis.__au.length);
					while(_g2 < _g11.length) tink_core__$Callback_Callback_$Impl_$.invoke(_g11[_g2++],tink_core_Noise.Noise);
				}
			});
		}
	},function() {
		last = null;
		firstTime = true;
		_gthis.__beforeUnmount();
	});
};
coconut_ui_View.__name__ = true;
coconut_ui_View.__super__ = coconut_ui_ViewBase;
coconut_ui_View.prototype = $extend(coconut_ui_ViewBase.prototype,{
	__beforeUnmount: function() {
		var _g = 0;
		var _g1 = this.__bu.splice(0,this.__bu.length);
		while(_g < _g1.length) {
			var c = _g1[_g];
			++_g;
			if(c != null) {
				c.cancel();
			}
		}
		var _g2 = 0;
		var _g3 = this.__bc.splice(0,this.__bu.length);
		while(_g2 < _g3.length) tink_core__$Callback_Callback_$Impl_$.invoke(_g3[_g2++],true);
	}
	,forceUpdate: function(callback) {
		this._coco_revision.set(tink_state__$State_State_$Impl_$.get_value(this._coco_revision) + 1);
		if(callback != null) {
			this.__au.push(tink_core__$Callback_Callback_$Impl_$.fromNiladic(callback));
		}
	}
});
var Stepper = function(__coco_data_) {
	this.__tink_defaults0 = { step : tink_state__$Observable_Observable_$Impl_$.const(1)};
	this.__slots = { step : new coconut_ui_tools_Slot(this,null), onconfirm : new coconut_ui_tools_Slot(this,null)};
	this.__coco_value = new tink_state__$State_SimpleState(0,null,null);
	this.__initAttributes(__coco_data_);
	coconut_ui_View.call(this,$bind(this,this.coconutRender),null,null,null,null,null);
};
Stepper.__name__ = true;
Stepper.fromHxx = function(attributes) {
	return React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(Stepper),attributes);
};
Stepper.__super__ = coconut_ui_View;
Stepper.prototype = $extend(coconut_ui_View.prototype,{
	coconutRender: function() {
		var tmp = $$tre;
		var tmp1 = react__$ReactType_ReactType_$Impl_$.fromString("div");
		var tmp2 = $$tre;
		var tmp3 = react__$ReactType_ReactType_$Impl_$.fromString("button");
		var _g = this;
		var param = tink_state__$State_State_$Impl_$.get_value(_g.__coco_value) - tink_state__$Observable_Observable_$Impl_$.get_value(this.__slots.step);
		_g.__coco_value.set(param);
		var tmp4 = { "$$typeof" : $$tre, type : react__$ReactType_ReactType_$Impl_$.fromString("span"), props : { children : tink_state__$State_State_$Impl_$.get_value(this.__coco_value)}, key : null, ref : null};
		var tmp5 = $$tre;
		var tmp6 = react__$ReactType_ReactType_$Impl_$.fromString("button");
		var _g1 = this;
		var param1 = tink_state__$State_State_$Impl_$.get_value(_g1.__coco_value) + tink_state__$Observable_Observable_$Impl_$.get_value(this.__slots.step);
		_g1.__coco_value.set(param1);
		return { "$$typeof" : tmp, type : tmp1, props : { 'class' : "counter", children : [{ "$$typeof" : tmp2, type : tmp3, props : { onclick : param, children : "-"}, key : null, ref : null},tmp4,{ "$$typeof" : tmp5, type : tmp6, props : { onclick : param1, children : "+"}, key : null, ref : null}]}, key : null, ref : null};
	}
	,get_step: function() {
		return tink_state__$Observable_Observable_$Impl_$.get_value(this.__slots.step);
	}
	,get_onconfirm: function() {
		return tink_state__$Observable_Observable_$Impl_$.get_value(this.__slots.onconfirm);
	}
	,get_value: function() {
		return tink_state__$State_State_$Impl_$.get_value(this.__coco_value);
	}
	,set_value: function(param) {
		this.__coco_value.set(param);
		return param;
	}
	,__initAttributes: function(attributes) {
		var this1 = attributes.step;
		this.__slots.step.setData(this1 == null ? this.__tink_defaults0.step : this1);
		this.__slots.onconfirm.setData(attributes.onconfirm);
	}
});
Math.__name__ = true;
var coconut_react__$Key_Key_$Impl_$ = {};
coconut_react__$Key_Key_$Impl_$.__name__ = true;
coconut_react__$Key_Key_$Impl_$.ofObj = function(o) {
	var id = o.__id__ || (o.__id__ = ++haxe_ds_ObjectMap.count);
	return id;
};
var coconut_ui__$ViewBase_Rewrapped = function(props,context) {
	React_Component.call(this,props,context);
};
coconut_ui__$ViewBase_Rewrapped.__name__ = true;
coconut_ui__$ViewBase_Rewrapped.fromHxx = function(props) {
	return React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(coconut_ui__$ViewBase_Rewrapped),props);
};
coconut_ui__$ViewBase_Rewrapped.__super__ = React_Component;
coconut_ui__$ViewBase_Rewrapped.prototype = $extend(React_Component.prototype,{
	componentDidMount: function() {
		this.props.target.componentDidMount();
	}
	,componentDidUpdate: function(_,_1) {
		this.props.target.componentDidUpdate(null,null);
	}
	,componentWillUnmount: function() {
		this.props.target.componentWillUnmount();
	}
	,render: function() {
		var _gthis = this;
		var this1 = this.link;
		if(this1 != null) {
			this1.cancel();
		}
		var ret = tink_state__$Observable_Observable_$Impl_$.measure(this.props.target.__rendered);
		this.link = ret.b.handle(tink_core__$Callback_Callback_$Impl_$.fromNiladic(function() {
			_gthis.forceUpdate();
		}));
		return ret.a;
	}
});
var coconut_ui_tools_Slot = function(owner,compare) {
	this.owner = owner;
	this.compare = compare == null ? function(a,b) {
		return a == b;
	} : compare;
};
coconut_ui_tools_Slot.__name__ = true;
coconut_ui_tools_Slot.prototype = {
	poll: function() {
		var _gthis = this;
		if(this.last == null) {
			if(this.data == null) {
				this.last = new tink_core_MPair(null,new tink_core_FutureTrigger());
			} else {
				var m = tink_state__$Observable_Observable_$Impl_$.measure(this.data);
				this.last = new tink_core_MPair(m.a,new tink_core_FutureTrigger());
				this.link = m.b.handle(($_=this.last.b,$bind($_,$_.trigger)));
			}
			this.last.b.handle(tink_core__$Callback_Callback_$Impl_$.fromNiladic(function() {
				_gthis.last = null;
			}));
		}
		return new tink_core_MPair(this.last.a,this.last.b);
	}
	,setData: function(data) {
		this.data = data;
		if(this.last != null) {
			var this1 = this.link;
			if(this1 != null) {
				this1.cancel();
			}
			if(data != null) {
				var _e = data;
				var m = tink_state__$Observable_Observable_$Impl_$.untracked(function() {
					return tink_state__$Observable_Observable_$Impl_$.measure(_e);
				});
				if(this.compare(m.a,this.last.a)) {
					this.link = m.b.handle(($_=this.last.b,$bind($_,$_.trigger)));
				} else {
					this.last.b.trigger(tink_core_Noise.Noise);
				}
			}
		}
	}
};
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ds_List = function() {
	this.length = 0;
};
haxe_ds_List.__name__ = true;
haxe_ds_List.prototype = {
	push: function(item) {
		var x = new haxe_ds__$List_ListNode(item,this.h);
		this.h = x;
		if(this.q == null) {
			this.q = x;
		}
		this.length++;
	}
	,first: function() {
		if(this.h == null) {
			return null;
		} else {
			return this.h.item;
		}
	}
	,pop: function() {
		if(this.h == null) {
			return null;
		}
		var x = this.h.item;
		this.h = this.h.next;
		if(this.h == null) {
			this.q = null;
		}
		this.length--;
		return x;
	}
};
var haxe_ds__$List_ListNode = function(item,next) {
	this.item = item;
	this.next = next;
};
haxe_ds__$List_ListNode.__name__ = true;
var haxe_ds_ObjectMap = function() {
	this.h = { __keys__ : { }};
};
haxe_ds_ObjectMap.__name__ = true;
haxe_ds_ObjectMap.prototype = {
	set: function(key,value) {
		var id = key.__id__ || (key.__id__ = ++haxe_ds_ObjectMap.count);
		this.h[id] = value;
		this.h.__keys__[id] = key;
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s += "\t";
				var tmp = n + "(";
				var _g = [];
				var _g1 = 0;
				var _g2 = con.__params__;
				while(_g1 < _g2.length) {
					var p = _g2[_g1];
					++_g1;
					_g.push(js_Boot.__string_rec(o[p],s));
				}
				return tmp + _g.join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var l = o.length;
			var i;
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = l;
			while(_g3 < _g11) {
				var i1 = _g3++;
				str += (i1 > 0 ? "," : "") + js_Boot.__string_rec(o[i1],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var React_Fragment = require("react").Fragment;
var React = require("react");
var react__$ReactType_ReactType_$Impl_$ = {};
react__$ReactType_ReactType_$Impl_$.__name__ = true;
react__$ReactType_ReactType_$Impl_$.fromString = function(s) {
	return s;
};
react__$ReactType_ReactType_$Impl_$.fromComp = function(cls) {
	if(cls.__jsxStatic != null) {
		return cls.__jsxStatic;
	}
	return cls;
};
var tink_core__$Callback_Callback_$Impl_$ = {};
tink_core__$Callback_Callback_$Impl_$.__name__ = true;
tink_core__$Callback_Callback_$Impl_$.invoke = function(this1,data) {
	if(tink_core__$Callback_Callback_$Impl_$.depth < 1000) {
		tink_core__$Callback_Callback_$Impl_$.depth++;
		this1(data);
		tink_core__$Callback_Callback_$Impl_$.depth--;
	} else {
		var _e = this1;
		var f = function(data1) {
			tink_core__$Callback_Callback_$Impl_$.invoke(_e,data1);
		};
		var data2 = data;
		tink_core__$Callback_Callback_$Impl_$.defer(function() {
			f(data2);
		});
	}
};
tink_core__$Callback_Callback_$Impl_$.fromNiladic = function(f) {
	return f;
};
tink_core__$Callback_Callback_$Impl_$.defer = function(f) {
	haxe_Timer.delay(f,0);
};
var tink_core__$Callback_SimpleLink = function(f) {
	this.f = f;
};
tink_core__$Callback_SimpleLink.__name__ = true;
tink_core__$Callback_SimpleLink.prototype = {
	cancel: function() {
		if(this.f != null) {
			this.f();
			this.f = null;
		}
	}
};
var tink_core__$Callback_ListCell = function(cb,list) {
	if(cb == null) {
		throw new js__$Boot_HaxeError("callback expected but null received");
	}
	this.cb = cb;
	this.list = list;
};
tink_core__$Callback_ListCell.__name__ = true;
tink_core__$Callback_ListCell.prototype = {
	clear: function() {
		this.list = null;
		this.cb = null;
	}
	,cancel: function() {
		var _g = this.list;
		if(_g != null) {
			this.clear();
			HxOverrides.remove(_g,this);
		}
	}
};
var tink_core__$Callback_CallbackList_$Impl_$ = {};
tink_core__$Callback_CallbackList_$Impl_$.__name__ = true;
tink_core__$Callback_CallbackList_$Impl_$.add = function(this1,cb) {
	var node = new tink_core__$Callback_ListCell(cb,this1);
	this1.push(node);
	return node;
};
tink_core__$Callback_CallbackList_$Impl_$.invoke = function(this1,data) {
	var _g = 0;
	var _g1 = this1.slice();
	while(_g < _g1.length) {
		var cell = _g1[_g];
		++_g;
		if(cell.cb != null) {
			tink_core__$Callback_Callback_$Impl_$.invoke(cell.cb,data);
		}
	}
};
tink_core__$Callback_CallbackList_$Impl_$.clear = function(this1) {
	var _g = 0;
	var _g1 = this1.splice(0,this1.length);
	while(_g < _g1.length) _g1[_g++].clear();
};
var tink_core_TypedError = function() { };
tink_core_TypedError.__name__ = true;
tink_core_TypedError.tryFinally = function(f,cleanup) {
	try { return f(); } finally { cleanup(); }
	return null;
};
var tink_core_Noise = $hxEnums["tink.core.Noise"] = { __ename__ : true, __constructs__ : ["Noise"]
	,Noise: {_hx_index:0,__enum__:"tink.core.Noise",toString:$estr}
};
var tink_core__$Future_SimpleFuture = function(f) {
	this.f = f;
};
tink_core__$Future_SimpleFuture.__name__ = true;
tink_core__$Future_SimpleFuture.prototype = {
	handle: function(callback) {
		return this.f(callback);
	}
};
var tink_core_FutureTrigger = function() {
	this.list = [];
};
tink_core_FutureTrigger.__name__ = true;
tink_core_FutureTrigger.prototype = {
	handle: function(callback) {
		var _g = this.list;
		if(_g == null) {
			tink_core__$Callback_Callback_$Impl_$.invoke(callback,this.result);
			return null;
		} else {
			return tink_core__$Callback_CallbackList_$Impl_$.add(_g,callback);
		}
	}
	,trigger: function(result) {
		if(this.list == null) {
			return false;
		} else {
			var list = this.list;
			this.list = null;
			this.result = result;
			tink_core__$Callback_CallbackList_$Impl_$.invoke(list,result);
			tink_core__$Callback_CallbackList_$Impl_$.clear(list);
			return true;
		}
	}
};
var tink_core__$Lazy_LazyFunc = function(f) {
	this.f = f;
};
tink_core__$Lazy_LazyFunc.__name__ = true;
tink_core__$Lazy_LazyFunc.prototype = {
	get: function() {
		if(this.f != null) {
			this.result = this.f();
			this.f = null;
		}
		return this.result;
	}
};
var tink_core_MPair = function(a,b) {
	this.a = a;
	this.b = b;
};
tink_core_MPair.__name__ = true;
var tink_state__$Observable_Observable_$Impl_$ = {};
tink_state__$Observable_Observable_$Impl_$.__name__ = true;
tink_state__$Observable_Observable_$Impl_$.get_value = function(this1) {
	return tink_state__$Observable_Observable_$Impl_$.measure(this1).a;
};
tink_state__$Observable_Observable_$Impl_$.measure = function(this1) {
	var before = tink_state__$Observable_Observable_$Impl_$.stack.first();
	tink_state__$Observable_Observable_$Impl_$.stack.push(this1);
	var p = this1.poll();
	var _g = ((before) instanceof tink_state__$Observable_AutoObservable) ? before : null;
	if(_g != null) {
		_g.subscribe(p.b);
	}
	tink_state__$Observable_Observable_$Impl_$.stack.pop();
	return p;
};
tink_state__$Observable_Observable_$Impl_$.bind = function(this1,options,cb) {
	var cb1;
	if(options == null) {
		cb1 = cb;
	} else if(options.comparator == null) {
		cb1 = cb;
	} else {
		var equal = options.comparator;
		var isFirst = true;
		var last = null;
		cb1 = function(data) {
			if(isFirst) {
				isFirst = false;
				tink_core__$Callback_Callback_$Impl_$.invoke(cb,data);
			} else if(!equal(last,data)) {
				tink_core__$Callback_Callback_$Impl_$.invoke(cb,data);
			}
			last = data;
		};
	}
	if(options == null) {
		var scheduled = false;
		var active = true;
		var updated = null;
		var link = null;
		var update = function() {
			if(active) {
				var next = tink_state__$Observable_Observable_$Impl_$.measure(this1);
				tink_core__$Callback_Callback_$Impl_$.invoke(cb1,next.a);
				scheduled = false;
				link = next.b.handle(updated);
			}
		};
		var doSchedule = function() {
			if(scheduled) {
				return;
			}
			scheduled = true;
			tink_state__$Observable_Observable_$Impl_$.schedule(update);
		};
		updated = tink_core__$Callback_Callback_$Impl_$.fromNiladic(doSchedule);
		doSchedule();
		return new tink_core__$Callback_SimpleLink(function() {
			if(active) {
				active = false;
				if(link != null) {
					link.cancel();
				}
			}
		});
	} else if(options.direct == null) {
		var scheduled1 = false;
		var active1 = true;
		var updated1 = null;
		var link1 = null;
		var update1 = function() {
			if(active1) {
				var next1 = tink_state__$Observable_Observable_$Impl_$.measure(this1);
				tink_core__$Callback_Callback_$Impl_$.invoke(cb1,next1.a);
				scheduled1 = false;
				link1 = next1.b.handle(updated1);
			}
		};
		var doSchedule1 = function() {
			if(scheduled1) {
				return;
			}
			scheduled1 = true;
			tink_state__$Observable_Observable_$Impl_$.schedule(update1);
		};
		updated1 = tink_core__$Callback_Callback_$Impl_$.fromNiladic(doSchedule1);
		doSchedule1();
		return new tink_core__$Callback_SimpleLink(function() {
			if(active1) {
				active1 = false;
				if(link1 != null) {
					link1.cancel();
				}
			}
		});
	} else if(options.direct == false) {
		var scheduled2 = false;
		var active2 = true;
		var updated2 = null;
		var link2 = null;
		var update2 = function() {
			if(active2) {
				var next2 = tink_state__$Observable_Observable_$Impl_$.measure(this1);
				tink_core__$Callback_Callback_$Impl_$.invoke(cb1,next2.a);
				scheduled2 = false;
				link2 = next2.b.handle(updated2);
			}
		};
		var doSchedule2 = function() {
			if(scheduled2) {
				return;
			}
			scheduled2 = true;
			tink_state__$Observable_Observable_$Impl_$.schedule(update2);
		};
		updated2 = tink_core__$Callback_Callback_$Impl_$.fromNiladic(doSchedule2);
		doSchedule2();
		return new tink_core__$Callback_SimpleLink(function() {
			if(active2) {
				active2 = false;
				if(link2 != null) {
					link2.cancel();
				}
			}
		});
	} else {
		var link3 = null;
		var update3 = null;
		update3 = function(_) {
			var next3 = tink_state__$Observable_Observable_$Impl_$.measure(this1);
			tink_core__$Callback_Callback_$Impl_$.invoke(cb1,next3.a);
			link3 = next3.b.handle(update3);
		};
		update3(tink_core_Noise.Noise);
		return new tink_core__$Callback_SimpleLink(function() {
			if(link3 != null) {
				link3.cancel();
			}
		});
	}
};
tink_state__$Observable_Observable_$Impl_$.schedule = function(f) {
	var _g = tink_state__$Observable_Observable_$Impl_$.scheduled;
	if(_g == null) {
		f();
	} else {
		_g.push(f);
		tink_state__$Observable_Observable_$Impl_$.scheduleUpdate();
	}
};
tink_state__$Observable_Observable_$Impl_$.scheduleUpdate = function() {
	if(!tink_state__$Observable_Observable_$Impl_$.isScheduled) {
		tink_state__$Observable_Observable_$Impl_$.isScheduled = true;
		if(tink_state__$Observable_Observable_$Impl_$.hasRAF) {
			window.requestAnimationFrame(function(_) {
				tink_state__$Observable_Observable_$Impl_$.scheduledRun();
			});
		} else {
			tink_core__$Callback_Callback_$Impl_$.defer(tink_state__$Observable_Observable_$Impl_$.scheduledRun);
		}
	}
};
tink_state__$Observable_Observable_$Impl_$.scheduledRun = function() {
	tink_state__$Observable_Observable_$Impl_$.isScheduled = false;
	tink_state__$Observable_Observable_$Impl_$.updatePending();
};
tink_state__$Observable_Observable_$Impl_$.updatePending = function(maxSeconds) {
	if(maxSeconds == null) {
		maxSeconds = .01;
	}
	var end = Date.now() / 1000 + maxSeconds;
	while(true) {
		var old = tink_state__$Observable_Observable_$Impl_$.scheduled;
		tink_state__$Observable_Observable_$Impl_$.scheduled = [];
		var _g = 0;
		while(_g < old.length) old[_g++]();
		if(!(tink_state__$Observable_Observable_$Impl_$.scheduled.length > 0 && Date.now() / 1000 < end)) {
			break;
		}
	}
	if(tink_state__$Observable_Observable_$Impl_$.scheduled.length > 0) {
		tink_state__$Observable_Observable_$Impl_$.scheduleUpdate();
		return true;
	} else {
		return false;
	}
};
tink_state__$Observable_Observable_$Impl_$.auto = function(f) {
	return new tink_state__$Observable_AutoObservable(f);
};
tink_state__$Observable_Observable_$Impl_$.const = function(value) {
	return new tink_state_ConstObservable(value);
};
tink_state__$Observable_Observable_$Impl_$.untracked = function(f) {
	tink_state__$Observable_Observable_$Impl_$.stack.push(null);
	return tink_core_TypedError.tryFinally(f,($_=tink_state__$Observable_Observable_$Impl_$.stack,$bind($_,$_.pop)));
};
var tink_state__$Observable_SimpleObservable = function(f) {
	this._poll = f;
};
tink_state__$Observable_SimpleObservable.__name__ = true;
tink_state__$Observable_SimpleObservable.prototype = {
	resetCache: function(_) {
		this.cache = null;
	}
	,poll: function() {
		var count = 0;
		var last = null;
		while(this.cache == null) {
			var cache = this.cache = this._poll();
			if(last == cache) {
				throw new js__$Boot_HaxeError("Polling loops on the same value");
			}
			last = cache;
			cache.b.handle($bind(this,this.resetCache));
			if(count++ >= 100) {
				throw new js__$Boot_HaxeError("Polling not concluded after 100 iterations");
			}
		}
		return this.cache;
	}
};
var tink_state_ConstObservable = function(value) {
	this.m = new tink_core_MPair(value,tink_state_ConstObservable.NEVER);
};
tink_state_ConstObservable.__name__ = true;
tink_state_ConstObservable.prototype = {
	poll: function() {
		return this.m;
	}
};
var tink_state__$Observable_AutoObservable = function(comp) {
	this.subscriptions = new haxe_ds_ObjectMap();
	var _gthis = this;
	tink_state__$Observable_SimpleObservable.call(this,function() {
		_gthis.subscriptions = new haxe_ds_ObjectMap();
		_gthis.trigger = new tink_core_FutureTrigger();
		return new tink_core_MPair(comp.f(),_gthis.trigger);
	});
};
tink_state__$Observable_AutoObservable.__name__ = true;
tink_state__$Observable_AutoObservable.__super__ = tink_state__$Observable_SimpleObservable;
tink_state__$Observable_AutoObservable.prototype = $extend(tink_state__$Observable_SimpleObservable.prototype,{
	subscribe: function(change) {
		if(this.subscriptions.h.__keys__[change.__id__] == null) {
			this.subscriptions.set(change,change.handle(($_=this.trigger,$bind($_,$_.trigger))));
		}
	}
});
var tink_state__$State_State_$Impl_$ = {};
tink_state__$State_State_$Impl_$.__name__ = true;
tink_state__$State_State_$Impl_$.get_value = function(this1) {
	return tink_state__$Observable_Observable_$Impl_$.get_value(this1);
};
var tink_state__$State_SimpleState = function(value,isEqual,guard) {
	this.value = value;
	this.isEqual = isEqual;
	this.guard = guard;
	this.arm();
};
tink_state__$State_SimpleState.__name__ = true;
tink_state__$State_SimpleState.prototype = {
	poll: function() {
		return this.next;
	}
	,arm: function() {
		this.trigger = new tink_core_FutureTrigger();
		this.next = new tink_core_MPair(this.value,this.trigger);
	}
	,set: function(value) {
		if(this.guard != null) {
			value = this.guard(value,this.value);
		}
		var b = this.value;
		if(this.isEqual == null ? value != b : !this.isEqual(value,b)) {
			this.value = value;
			var last = this.trigger;
			this.arm();
			last.trigger(tink_core_Noise.Noise);
		}
	}
};
var $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
Object.defineProperty(coconut_ui_ViewBase.prototype,"props",{ get : function() {
	return this.__props;
}, set : function(attr) {
	if(attr != null) {
		this.__props = attr;
		this.__initAttributes(attr);
	}
}});
String.__name__ = true;
Array.__name__ = true;
haxe_ds_ObjectMap.count = 0;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
coconut_ui_View.idCounter = 0;
tink_core__$Callback_Callback_$Impl_$.depth = 0;
tink_state__$Observable_Observable_$Impl_$.stack = new haxe_ds_List();
tink_state__$Observable_Observable_$Impl_$.scheduled = [];
tink_state__$Observable_Observable_$Impl_$.hasRAF = typeof window != 'undefined' && 'requestAnimationFrame' in window;
tink_state__$Observable_Observable_$Impl_$.isScheduled = false;
tink_state_ConstObservable.NEVER = new tink_core__$Future_SimpleFuture(function(_) {
	return null;
});
Main.main();
})();
